### ISSUE TITLE
[BUG?] -Dが機能していない

### ISSUE THREAD

**Issue by blacknon** [xztaityozx/surge#1]
output_delimiterが読まれてないため、1行に戻せてない気配

```shell
[uesugi@uesugi-MacBook-Pro][~/_rust/surge]                                                                               [BATTERY:100%] [main]
(｀・ω・´)  < seq 1 10 | xargs -n5 | surge -- gsed -r 's/.+/xxx_&/'                                             [2022/03/12 11:48:59 (土) JST]
xxx_1
xxx_2
xxx_3
xxx_4
xxx_5
xxx_6
xxx_7
xxx_8
xxx_9
xxx_10

```

**Comment by xztaityozx** [comment]
ありゃ～～～

**Comment by xztaityozx** [comment]
https://github.com/xztaityozx/surge/blob/0078f045919e4273e8c8e5a1b770fb9c0d5ec915/src/main.rs#L243

ここで `replace('\n', &arg.output_delimiter)` し忘れてました…

**Comment by xztaityozx** [comment]
これだと末尾に 'arg.output_delimiter'がついちゃうから別にトリムしないとだめか

**Comment by blacknon** [comment]
全部一括で`\n`を置換しちゃうと、思ってない動作になりそうですね 🤔 
Vecをjoinさせるほうが良いような気も…？

(~~243ではなく、handle join時に処理する方法があると良いのかも？~~ => handle join前にtrimが必要なのかも？)

**Comment by xztaityozx** [comment]
なるほど。trim_end() してから replace するとよさそうです！

**Comment by xztaityozx** [comment]
でも本質は

> Vecをjoinさせるほうが良いような気も…？

な気もしますね…。

**Comment by xztaityozx** [comment]
resolved つけたら勝手にcloseされちゃったので、Reopen
